version: '3.8'

services:
  server:
    build:
      context: .
    container_name: restotech_standard_server
    ports:
      - 8180:80
      - 40443:443
    command: bash -c "service apache2 start && bash"
    tty: true
    depends_on:
      - database

  database:
    image: mariadb
    container_name: restotech_mariadb_server
    environment:
       MYSQL_ROOT_PASSWORD: Root123456Restotech
